spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456123456
mybatis:
  type-aliases-package: com.silenthill.redbook.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
